---
title: "Estimating Seroprevalence of SARS-CoV-2"
author: "Samuel Rosin"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  rmarkdown::github_document:
    html_preview: true 
    toc: yes
   # code_folding: hide
   # theme: cerulean
   # toc_float: yes
---

This reanalysis of the ScreenNC study accompanies the manuscript "Estimating Seroprevalence of SARS-CoV-2" by Samuel Rosin, Bonnie Shook-Sa, Stephen H. Cole, and Michael G. Hudgens. ScreenNC initially studied COVID-19 asymptomatic patients who sought medical care unrelated to COVID-19 at any of 11 outpatient clinical sites associated with the UNC Health Network and emergency room sites between April 28 and June 19, 2020. A blood draw was taken from each patient and tested for the presence of antibodies to SARS-CoV-2. This serological study estimates the prevalence of antibodies for SARS-CoV-2 in the study sample and among larger populations.

The initial analysis was published in the paper ["SARS-CoV-2 Seroprevalence Among a Southern U.S. Population Indicates Limited Asymptomatic Spread under Physical Distancing Measures"](https://mbio.asm.org/content/11/5/e02426-20). Interested readers can find extra detail about ScreenNC and the associated dataset by reading that paper and its [supplementary information and code](https://bitbucket.org/dittmerlab/public_screen_nc/src/public/). 



```{r setup, warning = FALSE}
# load libraries and files of helper functions, set global variables and options, etc.
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(testit)
library(table1)
library(lubridate)
library(knitr)
set.seed(2021) # set random seed so procedures are replicable

other_races <- c("American Indian or Alaska Native", "Native Hawaiian or 
                 Other Pacific Islander", "Other Race", "Other/Hispanic") # names of races grouped into 'Other Race' 
kable_format <- "pandoc" # format used for kable 
vars_std <- c("sex_name", "race_name","age_group") # variables to standardize over
vars_table1 <- c("sex_name", "race_name", "ethnic_group_name", "age_group") # variables to include in table 1


# source files of helper functions
#source(here::here("screenNC_descriptive_helper_fns.R")) 
#source(here::here("screennc_reanalysis_stats_fns.R")) 

```

